### ISSUE TITLE
Set up UIs for unauthenticated users/guests

### ISSUE THREAD

**Issue by reichert621** [reichert621/blog#157]
Allow guests to:
- take the assessment(s) without logging in, just to get a quick result that isn't saved anywhere
- view/check off tasks for the day to gauge productivity (optional, but potentially good as a preview for the app)

**Comment by reichert621** [comment]
Done!

- http://ensou.co/example/checklist
- http://ensou.co/example/scorecard

**Comment by stopachka** [comment]
Awesome!!
